openapi: 3.1.0
info:
  title: ''
  description: ''
  version: ''
servers:
  - url: https://wwwcie.ups.com/api
    description: Customer Integration Environment
  - url: https://onlinetools.ups.com/api
    description: Production
tags:
  - name: UPS Track Alert
    description:
      $ref: "UPSTrackAlert-Ready.yaml#/info/description"
  - name: UPS Track Alert with Photo
    description:
      $ref: "UPSTrackAlertEnhanced-Ready.yaml#/info/description"
  - name: Delivery Defense
    description:
      $ref: "DeliveryDefense-Ready.yaml#/info/description"
  - name: Delivery Intercept
    description:
      $ref: "DeliveryIntercept.yaml#/info/description"
  - name: Export Assure
    description:
      $ref: "UPSExportAssure.yaml#/info/description"
  - name: Interactive Description
    description:
      $ref: "InteractiveDescriptionGuidance.yaml#/info/description"
  - name: Address Validation
    description: 
      $ref: "AddressValidation-Ready.yaml#/info/description"
  - name: Commerce Guard
    description: 
      $ref: "CommerceGuard.yaml#/info/description"
  - name: Dangerous Goods
    description: 
      $ref: "DangerousGoods-Ready.yaml#/info/description"
  #- name: Global Checkout
  #  description:
  #    $ref: "GlobalCheckout.yaml#/info/description"
  - name: Landed Cost
    description: 
      $ref: "LandedCost-Ready.yaml#/info/description"
  - name: Locator
    description: 
      $ref: "Locator.yaml#/info/description"
  - name: OAuth Auth Code
    description: 
      $ref: "OAuthAuthCode-Ready.yaml#/info/description"
  - name: OAuth Client Credentials
    description: 
      $ref: "OAuthClientCredentials-Ready.yaml#/info/description"
  - name: Paperless
    description: 
      $ref: "Paperless-Ready.yaml#/info/description"
  - name: Pickup
    description:
      $ref: "Pickup.yaml#/info/description"
  - name: Pre-Notification
    description:
      $ref: "PreNotification-Ready.yaml#/info/description"
  - name: Quantum View
    description:
      $ref: "QuantumView-Ready.yaml#/info/description"
  - name: Rating
    description:
      $ref: "Rating.yaml#/info/description"
  - name: Shipping
    description:
      $ref: "Shipping.yaml#/info/description"
  - name: Time in Transit
    description:
      $ref: "TimeInTransit.yaml#/info/description"
  - name: Tracking
    description:
      $ref: "Tracking-Ready.yaml#/info/description"
  - name: World Ease Shipment Management - Shipment
    description:
      $ref: "WorldEaseShipmentManagement.yaml#/info/description"
paths:
  "/addressvalidation/{version}/{requestoption}":
    "$ref": "AddressValidation-Ready.yaml#/paths/~1addressvalidation~1{version}~1{requestoption}"
  "/addressvalidation/{deprecatedVersion}/{requestoption}":
    "$ref": "AddressValidation-Ready.yaml#/paths/~1addressvalidation~1{deprecatedVersion}~1{requestoption}"
  "/dangerousgoods/{version}/chemicalreferencedata":
    "$ref": "DangerousGoods-Ready.yaml#/paths/~1dangerousgoods~1{version}~1chemicalreferencedata"
  "/dangerousgoods/{version}/acceptanceauditprecheck":
    "$ref": "DangerousGoods-Ready.yaml#/paths/~1dangerousgoods~1{version}~1acceptanceauditprecheck"
  "/dangerousgoods/{deprecatedVersion}/chemicalreferencedata":
    "$ref": "DangerousGoods-Ready.yaml#/paths/~1dangerousgoods~1{deprecatedVersion}~1chemicalreferencedata"
  "/dangerousgoods/{deprecatedVersion}/acceptanceauditprecheck":
    "$ref": "DangerousGoods-Ready.yaml#/paths/~1dangerousgoods~1{deprecatedVersion}~1acceptanceauditprecheck"
  "/landedcost/{version}/quotes":
    "$ref": "LandedCost-Ready.yaml#/paths/~1landedcost~1{version}~1quotes"
  "/locations/{version}/search/availabilities/{reqOption}":
    "$ref": "Locator.yaml#/paths/~1locations~1{version}~1search~1availabilities~1{reqOption}"
  "/locations/{deprecatedVersion}/search/availabilities/{reqOption}":
    "$ref": "Locator.yaml#/paths/~1locations~1{deprecatedVersion}~1search~1availabilities~1{reqOption}"
  "/v1/oauth/authorize":
    "$ref": "OAuthAuthCode-Ready.yaml#/paths/~1v1~1oauth~1authorize"
  "/v1/oauth/token":
    "$ref": "OAuthAuthCode-Ready.yaml#/paths/~1v1~1oauth~1token"
  "/v1/oauth/refresh":
    "$ref": "OAuthAuthCode-Ready.yaml#/paths/~1v1~1oauth~1refresh"
  "/security/v1/oauth/token":
    "$ref": "OAuthClientCredentials-Ready.yaml#/paths/~1security~1v1~1oauth~1token"
  "/paperlessdocuments/{version}/upload":
    "$ref": "Paperless-Ready.yaml#/paths/~1paperlessdocuments~1{version}~1upload"
  "/paperlessdocuments/{version}/image":
    "$ref": "Paperless-Ready.yaml#/paths/~1paperlessdocuments~1{version}~1image"
  "/paperlessdocuments/{version}/DocumentId/ShipperNumber":
    "$ref": "Paperless-Ready.yaml#/paths/~1paperlessdocuments~1{version}~1DocumentId~1ShipperNumber"
  "/paperlessdocuments/{deprecatedVersion}/upload":
    "$ref": "Paperless-Ready.yaml#/paths/~1paperlessdocuments~1{deprecatedVersion}~1upload"
  "/paperlessdocuments/{deprecatedVersion}/image":
    "$ref": "Paperless-Ready.yaml#/paths/~1paperlessdocuments~1{deprecatedVersion}~1image"
  "/paperlessdocuments/{deprecatedVersion}/DocumentId/ShipperNumber":
    "$ref": "Paperless-Ready.yaml#/paths/~1paperlessdocuments~1{deprecatedVersion}~1DocumentId~1ShipperNumber"
  "/shipments/{version}/pickup/{pickuptype}":
    "$ref": "Pickup.yaml#/paths/~1shipments~1{version}~1pickup~1{pickuptype}"
  "/shipments/{version}/pickup/{CancelBy}":
    "$ref": "Pickup.yaml#/paths/~1shipments~1{version}~1pickup~1{CancelBy}"
  "/pickupcreation/{version}/pickup":
    "$ref": "Pickup.yaml#/paths/~1pickupcreation~1{version}~1pickup"
  "/pickup/{version}/countries/{countrycode}":
    "$ref": "Pickup.yaml#/paths/~1pickup~1{version}~1countries~1{countrycode}"
  "/pickup/{version}/servicecenterlocations":
    "$ref": "Pickup.yaml#/paths/~1pickup~1{version}~1servicecenterlocations"
  "/shipments/{deprecatedVersion}/pickup/{CancelBy}":
    "$ref": "Pickup.yaml#/paths/~1shipments~1{deprecatedVersion}~1pickup~1{CancelBy}"
  "/pickupcreation/{deprecatedVersion}/pickup":
    "$ref": "Pickup.yaml#/paths/~1pickupcreation~1{deprecatedVersion}~1pickup"
  "/dangerousgoods/{version}/prenotification":
    "$ref": "PreNotification-Ready.yaml#/paths/~1dangerousgoods~1{version}~1prenotification"
  "/dangerousgoods/{deprecatedVersion}/prenotification":
    "$ref": "PreNotification-Ready.yaml#/paths/~1dangerousgoods~1{deprecatedVersion}~1prenotification"
  "/quantumview/{version}/events":
    "$ref": "QuantumView-Ready.yaml#/paths/~1quantumview~1{version}~1events"
  "/quantumview/{deprecatedVersion}/events":
    "$ref": "QuantumView-Ready.yaml#/paths/~1quantumview~1{deprecatedVersion}~1events"
  "/rating/{version}/{requestoption}":
    "$ref": "Rating.yaml#/paths/~1rating~1{version}~1{requestoption}"
  "/rating/{deprecatedVersion}/{requestoption}":
    "$ref": "Rating.yaml#/paths/~1rating~1{deprecatedVersion}~1{requestoption}"
  "/shipments/{version}/ship":
    "$ref": "Shipping.yaml#/paths/~1shipments~1{version}~1ship"
  "/shipments/{version}/void/cancel/{shipmentidentificationnumber}":
    "$ref": "Shipping.yaml#/paths/~1shipments~1{version}~1void~1cancel~1{shipmentidentificationnumber}"
  "/labels/{version}/recovery":
    "$ref": "Shipping.yaml#/paths/~1labels~1{version}~1recovery"
  "/shipments/{deprecatedVersion}/ship":
    "$ref": "Shipping.yaml#/paths/~1shipments~1{deprecatedVersion}~1ship"
  "/shipments/{deprecatedVersion}/void/cancel/{shipmentidentificationnumber}":
    "$ref": "Shipping.yaml#/paths/~1shipments~1{deprecatedVersion}~1void~1cancel~1{shipmentidentificationnumber}"
  "/shipments/{version}/transittimes":
    "$ref": "TimeInTransit.yaml#/paths/~1shipments~1{version}~1transittimes"
  "/track/v1/details/{inquiryNumber}":
    "$ref": "Tracking-Ready.yaml#/paths/~1track~1v1~1details~1{inquiryNumber}"
  "/track/v1/reference/details/{referenceNumber}":
    "$ref": "Tracking-Ready.yaml#/paths/~1track~1v1~1reference~1details~1{referenceNumber}"
  "/track/{version}/subscription/enhanced/package":
    "$ref": "UPSTrackAlertEnhanced.yaml#/paths/~1subscription~1enhanced~1package"
  "/deliveryintercept/{version}/charges/{tracking_number}":
    "$ref": "DeliveryIntercept.yaml#/paths/~1charges~1{tracking_number}"
  "/deliveryintercept/{version}/eligibility/intercept/{tracking_number}":
    "$ref": "DeliveryIntercept.yaml#/paths/~1eligibility~1intercept~1{tracking_number}"
  "/deliveryintercept/{version}/redirect/address/{tracking_number}":
    "$ref": "DeliveryIntercept.yaml#/paths/~1redirect~1address~1{tracking_number}"
  "/deliveryintercept/{version}/willcall/{tracking_number}":
    "$ref": "DeliveryIntercept.yaml#/paths/~1willcall~1{tracking_number}"
  "/deliveryintercept/{version}/return/{tracking_number}":
    "$ref": "DeliveryIntercept.yaml#/paths/~1return~1{tracking_number}"
  "/deliveryintercept/{version}/reschedule/{tracking_number}":
    "$ref": "DeliveryIntercept.yaml#/paths/~1reschedule~1{tracking_number}"
  "/deliveryintercept/{version}/cancel/{tracking_number}":
    "$ref": "DeliveryIntercept.yaml#/paths/~1cancel~1{tracking_number}"
  "/deliverydefense/external/v1.0/address/score":
    "$ref": "DeliveryDefense-Ready.yaml#/paths/~1address~1score"
  "/brokerage/{version}/importexport/exportassure":
    "$ref": "UPSExportAssure.yaml#/paths/~1importexport~1exportassure"
  "/export-assure/{version}/interactive":
    "$ref": "InteractiveDescriptionGuidance.yaml#/paths/~1interactive"
  "/export-assure/{version}/interactive/{sessionId}":
    "$ref": "InteractiveDescriptionGuidance.yaml#/paths/~1interactive~1{sessionId}"
  "/export-assure/{version}/interactive/feedback/{sessionId}":
    "$ref": "InteractiveDescriptionGuidance.yaml#/paths/~1interactive~1feedback~1{sessionId}"
  #"/brokerage/{version}/content/glc/request-quote":
  #  "$ref": "GlobalCheckout.yaml#/paths/~1content~1glc~1request-quote"
  "/ship/{version}/master-shipment/closeout/{shipment-gccn}":
    "$ref": "WorldEaseShipmentManagement.yaml#/paths/~1master-shipment~1closeout~1{shipment-gccn}"
  "/ship/{version}/master-shipment/{shipment-gccn}":
    "$ref": "WorldEaseShipmentManagement.yaml#/paths/~1master-shipment~1{shipment-gccn}"
  "/ship/{version}/child-shipment/{shipment-gccn}/{tracking-number}":
    "$ref": "WorldEaseShipmentManagement.yaml#/paths/~1child-shipment~1{shipment-gccn}~1{tracking-number}"
  "/track/{version}/subscription/standard/package":
    "$ref": "UPSTrackAlert-Ready.yaml#/paths/~1subscription~1standard~1package"
  "/commerce-guard/{version}/verify":
    "$ref": "CommerceGuard.yaml#/paths/~1commerce-guard~1{version}~1verify"
webhooks:
  TrackingEvent:
    "$ref": "UPSTrackAlert-Ready.yaml#/webhooks/TrackingEvent"
  TrackingEventEnhanced:
    "$ref": "UPSTrackAlertEnhanced-Ready.yaml#/webhooks/TrackingEventEnhanced"                     
components:
  securitySchemes:
    OAuth2:
      $ref: 'AddressValidation-Ready.yaml#/components/securitySchemes/OAuth2'
    BasicAuth:
      $ref: 'OAuthClientCredentials-Ready.yaml#/components/securitySchemes/BasicAuth'
    BasicAuthGenerate:
      $ref: 'OAuthAuthCode-Ready.yaml#/components/securitySchemes/BasicAuthGenerate'
    BasicAuthRefresh:
      $ref: 'OAuthAuthCode-Ready.yaml#/components/securitySchemes/BasicAuthRefresh'