openapi: 3.1.0
info:
  title: ''
  description: ''
  version: ''
servers:
  - url: https://wwwcie.ups.com/api
    description: Customer Integration Environment
  - url: https://onlinetools.ups.com/api
    description: Production
tags:
  - name: UPS Track Alert
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/UPSTrackAlert.yaml#/info/description"
  - name: UPS Track Alert with Photo
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/UPSTrackAlertEnhanced.yaml#/info/description"
  - name: Export Assure
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/UPSExportAssure.yaml#/info/description"
  - name: Interactive Description
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/InteractiveDescriptionGuidance.yaml#/info/description"
  - name: Address Validation
    description: 
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/AddressValidation.yaml#/info/description"
  - name: Dangerous Goods
    description: 
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/DangerousGoods.yaml#/info/description"
  - name: Forwarding
    description: 
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Forwarding.yaml#/info/description"
  #- name: Global Checkout
  #  description:
  #    $ref: "GlobalCheckout.yaml#/info/description"
  - name: Landed Cost
    description: 
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/LandedCost.yaml#/info/description"
  - name: Locator
    description: 
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Locator.yaml#/info/description"
  - name: OAuth Auth Code
    description: 
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/OAuthAuthCode.yaml#/info/description"
  - name: OAuth Client Credentials
    description: 
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/OAuthClientCredentials.yaml#/info/description"
  - name: Paperless
    description: 
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Paperless.yaml#/info/description"
  - name: Pickup
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Pickup.yaml#/info/description"
  - name: Pre-Notification
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/PreNotification.yaml#/info/description"
  - name: Quantum View
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/QuantumView.yaml#/info/description"
  - name: Rating
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Rating.yaml#/info/description"
  - name: Shipping
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Shipping.yaml#/info/description"
  - name: TradeDirect
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/TradeDirect.yaml#/info/description"
  - name: Time in Transit
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/TimeInTransit.yaml#/info/description"
  - name: Tracking
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Tracking.yaml#/info/description"
  - name: World Ease Shipment Management - Shipment
    description:
      $ref: "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/WorldEaseShipmentManagement.yaml#/info/description"
paths:
  "/addressvalidation/{version}/{requestoption}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/AddressValidation.yaml#/paths/~1addressvalidation~1{version}~1{requestoption}"
  "/addressvalidation/{deprecatedVersion}/{requestoption}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/AddressValidation.yaml#/paths/~1addressvalidation~1{deprecatedVersion}~1{requestoption}"
  "/dangerousgoods/{version}/chemicalreferencedata":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/DangerousGoods.yaml#/paths/~1dangerousgoods~1{version}~1chemicalreferencedata"
  "/dangerousgoods/{version}/acceptanceauditprecheck":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/DangerousGoods.yaml#/paths/~1dangerousgoods~1{version}~1acceptanceauditprecheck"
  "/dangerousgoods/{deprecatedVersion}/chemicalreferencedata":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/DangerousGoods.yaml#/paths/~1dangerousgoods~1{deprecatedVersion}~1chemicalreferencedata"
  "/dangerousgoods/{deprecatedVersion}/acceptanceauditprecheck":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/DangerousGoods.yaml#/paths/~1dangerousgoods~1{deprecatedVersion}~1acceptanceauditprecheck"
  "/forwarding/{version}/air/rate":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Forwarding.yaml#/paths/~1air~1rate"
  "/forwarding/{version}/air/orders":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Forwarding.yaml#/paths/~1air~1orders"
  "/forwarding/{version}/air/orders/print-label":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Forwarding.yaml#/paths/~1air~1orders~1print-label"
  "/forwarding/{version}/air/orders/postpone":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Forwarding.yaml#/paths/~1air~1orders~1postpone"
  "/forwarding/{version}/air/orders/search":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Forwarding.yaml#/paths/~1air~1orders~1search"
  "/forwarding/{version}/air/shipment":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Forwarding.yaml#/paths/~1air~1shipment"
  "/forwarding/{version}/air/utility/city-details":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Forwarding.yaml#/paths/~1air~1utility~1city-details"
  "/forwarding/{version}/payment/status/{session_id}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Forwarding.yaml#/paths/~1payment~1status~1{session_id}"
  "/landedcost/{version}/quotes":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/LandedCost.yaml#/paths/~1landedcost~1{version}~1quotes"
  "/locations/{version}/search/availabilities/{reqOption}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Locator.yaml#/paths/~1locations~1{version}~1search~1availabilities~1{reqOption}"
  "/locations/{deprecatedVersion}/search/availabilities/{reqOption}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Locator.yaml#/paths/~1locations~1{deprecatedVersion}~1search~1availabilities~1{reqOption}"
  "/v1/oauth/authorize":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/OAuthAuthCode.yaml#/paths/~1v1~1oauth~1authorize"
  "/v1/oauth/token":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/OAuthAuthCode.yaml#/paths/~1v1~1oauth~1token"
  "/v1/oauth/refresh":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/OAuthAuthCode.yaml#/paths/~1v1~1oauth~1refresh"
  "/security/v1/oauth/token":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/OAuthClientCredentials.yaml#/paths/~1security~1v1~1oauth~1token"
  "/paperlessdocuments/{version}/upload":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Paperless.yaml#/paths/~1paperlessdocuments~1{version}~1upload"
  "/paperlessdocuments/{version}/image":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Paperless.yaml#/paths/~1paperlessdocuments~1{version}~1image"
  "/paperlessdocuments/{version}/DocumentId/ShipperNumber":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Paperless.yaml#/paths/~1paperlessdocuments~1{version}~1DocumentId~1ShipperNumber"
  "/paperlessdocuments/{deprecatedVersion}/upload":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Paperless.yaml#/paths/~1paperlessdocuments~1{deprecatedVersion}~1upload"
  "/paperlessdocuments/{deprecatedVersion}/image":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Paperless.yaml#/paths/~1paperlessdocuments~1{deprecatedVersion}~1image"
  "/paperlessdocuments/{deprecatedVersion}/DocumentId/ShipperNumber":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Paperless.yaml#/paths/~1paperlessdocuments~1{deprecatedVersion}~1DocumentId~1ShipperNumber"
  "/shipments/{version}/pickup/{pickuptype}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Pickup.yaml#/paths/~1shipments~1{version}~1pickup~1{pickuptype}"
  "/shipments/{version}/pickup/{CancelBy}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Pickup.yaml#/paths/~1shipments~1{version}~1pickup~1{CancelBy}"
  "/pickupcreation/{version}/pickup":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Pickup.yaml#/paths/~1pickupcreation~1{version}~1pickup"
  "/pickup/{version}/countries/{countrycode}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Pickup.yaml#/paths/~1pickup~1{version}~1countries~1{countrycode}"
  "/pickup/{version}/servicecenterlocations":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Pickup.yaml#/paths/~1pickup~1{version}~1servicecenterlocations"
  "/shipments/{deprecatedVersion}/pickup/{CancelBy}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Pickup.yaml#/paths/~1shipments~1{deprecatedVersion}~1pickup~1{CancelBy}"
  "/pickupcreation/{deprecatedVersion}/pickup":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Pickup.yaml#/paths/~1pickupcreation~1{deprecatedVersion}~1pickup"
  "/dangerousgoods/{version}/prenotification":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/PreNotification.yaml#/paths/~1dangerousgoods~1{version}~1prenotification"
  "/dangerousgoods/{deprecatedVersion}/prenotification":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/PreNotification.yaml#/paths/~1dangerousgoods~1{deprecatedVersion}~1prenotification"
  "/quantumview/{version}/events":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/QuantumView.yaml#/paths/~1quantumview~1{version}~1events"
  "/quantumview/{deprecatedVersion}/events":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/QuantumView.yaml#/paths/~1quantumview~1{deprecatedVersion}~1events"
  "/rating/{version}/{requestoption}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Rating.yaml#/paths/~1rating~1{version}~1{requestoption}"
  "/rating/{deprecatedVersion}/{requestoption}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Rating.yaml#/paths/~1rating~1{deprecatedVersion}~1{requestoption}"
  "/shipments/{version}/ship":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Shipping.yaml#/paths/~1shipments~1{version}~1ship"
  "/shipments/{version}/void/cancel/{shipmentidentificationnumber}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Shipping.yaml#/paths/~1shipments~1{version}~1void~1cancel~1{shipmentidentificationnumber}"
  "/labels/{version}/recovery":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Shipping.yaml#/paths/~1labels~1{version}~1recovery"
  "/shipments/{deprecatedVersion}/ship":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Shipping.yaml#/paths/~1shipments~1{deprecatedVersion}~1ship"
  "/shipments/{deprecatedVersion}/void/cancel/{shipmentidentificationnumber}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Shipping.yaml#/paths/~1shipments~1{deprecatedVersion}~1void~1cancel~1{shipmentidentificationnumber}"
  "/ship/tradedirect/{version}/master-shipments/{usi-number}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/TradeDirect.yaml#/paths/~1master-shipments~1{usi-number}"
  "/ship/tradedirect/{version}/master-shipments/{usi-number}/child-shipments/{tracking-number}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/TradeDirect.yaml#/paths/~1master-shipments~1{usi-number}~1child-shipments~1{tracking-number}"
  "/ship/tradedirect/{version}/master-shipments/{usi-number}/closeout":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/TradeDirect.yaml#/paths/~1master-shipments~1{usi-number}~1closeout"
  "/ship/tradedirect/{version}/master-shipments/{usi-number}/ltl-child-shipments/{sub-pro-number}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/TradeDirect.yaml#/paths/~1master-shipments~1{usi-number}~1ltl-child-shipments~1{sub-pro-number}"
  "/ship/tradedirect/{version}/master-shipments/documents":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/TradeDirect.yaml#/paths/~1master-shipments~1documents"
  "/shipments/{version}/transittimes":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/TimeInTransit.yaml#/paths/~1shipments~1{version}~1transittimes"
  "/track/v1/details/{inquiryNumber}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Tracking.yaml#/paths/~1track~1v1~1details~1{inquiryNumber}"
  "/track/v1/reference/details/{referenceNumber}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/Tracking.yaml#/paths/~1track~1v1~1reference~1details~1{referenceNumber}"
  "/track/{version}/subscription/enhanced/package":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/UPSTrackAlertEnhanced.yaml#/paths/~1subscription~1enhanced~1package"
  "/brokerage/{version}/importexport/exportassure":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/UPSExportAssure.yaml#/paths/~1importexport~1exportassure"
  "/export-assure/{version}/interactive":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/InteractiveDescriptionGuidance.yaml#/paths/~1interactive"
  "/export-assure/{version}/interactive/{sessionId}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/InteractiveDescriptionGuidance.yaml#/paths/~1interactive~1{sessionId}"
  "/export-assure/{version}/interactive/feedback/{sessionId}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/InteractiveDescriptionGuidance.yaml#/paths/~1interactive~1feedback~1{sessionId}"
  "/ship/{version}/master-shipment/closeout/{shipment-gccn}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/WorldEaseShipmentManagement.yaml#/paths/~1master-shipment~1closeout~1{shipment-gccn}"
  "/ship/{version}/master-shipment/{shipment-gccn}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/WorldEaseShipmentManagement.yaml#/paths/~1master-shipment~1{shipment-gccn}"
  "/ship/{version}/child-shipment/{shipment-gccn}/{tracking-number}":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/WorldEaseShipmentManagement.yaml#/paths/~1child-shipment~1{shipment-gccn}~1{tracking-number}"
  "/track/{version}/subscription/standard/package":
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/UPSTrackAlert.yaml#/paths/~1subscription~1standard~1package"
webhooks:
  TrackingEvent:
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/UPSTrackAlert.yaml#/webhooks/TrackingEvent"
  TrackingEventEnhanced:
    "$ref": "https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/UPSTrackAlertEnhanced.yaml#/webhooks/TrackingEventEnhanced"                     
components:
  securitySchemes:
    OAuth2:
      $ref: 'https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/AddressValidation.yaml#/components/securitySchemes/OAuth2'
    BasicAuth:
      $ref: 'https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/OAuthClientCredentials.yaml#/components/securitySchemes/BasicAuth'
    BasicAuthGenerate:
      $ref: 'https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/OAuthAuthCode.yaml#/components/securitySchemes/BasicAuthGenerate'
    BasicAuthRefresh:

      $ref: 'https://raw.githubusercontent.com/UPS-API/api-documentation/refs/heads/ups-apis-redocly/OAuthAuthCode.yaml#/components/securitySchemes/BasicAuthRefresh'


