openapi: 3.1.0
info:
  title: ''
  description: ''
  version: ''
servers:
  - url: https://wwwcie.ups.com/api
    description: Customer Integration Environment
  - url: https://onlinetools.ups.com/api
    description: Production
tags:
  - name: UPS Track Alert
    description:
      $ref: "https://github.com/UPS-API/api-documentation/blob/ups-apis-redocly/UPSTrackAlert.yaml#/info/description"
  - name: UPS Track Alert with Photo
    description:
      $ref: "https://github.com/UPS-API/api-documentation/blob/ups-apis-redocly/UPSTrackAlertEnhanced.yaml#/info/description"
  
paths:
  "/track/{version}/subscription/enhanced/package":
    "$ref": "https://github.com/UPS-API/api-documentation/blob/ups-apis-redocly/UPSTrackAlertEnhanced.yaml#/paths/~1subscription~1enhanced~1package"
  "/track/{version}/subscription/standard/package":
    "$ref": "https://github.com/UPS-API/api-documentation/blob/ups-apis-redocly/UPSTrackAlert.yaml#/paths/~1subscription~1standard~1package"
  
webhooks:
  TrackingEvent:
    "$ref": "https://github.com/UPS-API/api-documentation/blob/ups-apis-redocly/UPSTrackAlert.yaml#/webhooks/TrackingEvent"
  TrackingEventEnhanced:
    "$ref": "https://github.com/UPS-API/api-documentation/blob/ups-apis-redocly/UPSTrackAlertEnhanced.yaml#/webhooks/TrackingEventEnhanced"                     
components:
  securitySchemes:
    OAuth2:
      $ref: 'https://github.com/UPS-API/api-documentation/blob/ups-apis-redocly/UPSTrackAlert.yaml#/components/securitySchemes/OAuth2'
    BasicAuth:
      $ref: 'https://github.com/UPS-API/api-documentation/blob/ups-apis-redocly/UPSTrackAlert.yaml#/components/securitySchemes/BasicAuth'
    BasicAuthGenerate:
      $ref: 'https://github.com/UPS-API/api-documentation/blob/ups-apis-redocly/UPSTrackAlert.yaml#/components/securitySchemes/BasicAuthGenerate'
    BasicAuthRefresh:

      $ref: 'https://github.com/UPS-API/api-documentation/blob/ups-apis-redocly/UPSTrackAlert.yaml#/components/securitySchemes/BasicAuthRefresh'
