openapi: 3.1.0
info:
  title: PIN Management System API v1
  description: |
    The Protected Delivery Token or the PIN Management System API is a part of Verified Delivery that will offer shippers extra security to ensure the package is delivered to the intended recipient. A secure PIN will be required to release the package for delivery.
  version: "1.0"
tags:
  - name: tokens
    description: "A Public API which handles operations related to creating a token"
  - name: pins
    description: "Operations related to retrieving a PIN by token and retrieving PINs for the list of tracking numbers"
  - name: epra
    description: "Operations related to retrieving the EPRA release code and related actions for a given tracking number"
servers:
  - url: https://onlinetools.ups.com/api/pin-mgmt-sys/{version}
    description: external url for PIN Management System
    variables:
      version:
        description: API version
        default: v1
        enum: 
          - v1
paths:
  /pins/token:
    post:
      tags:
        - Protected Delivery Token
      operationId: generateToken
      summary: Generate Token
      description: |
        This endpoint is used to generate a token using Shipper generated PIN
      parameters:
        - $ref: '#/components/parameters/transID'
        - $ref: '#/components/parameters/transactionSrc'
      security:
        - OAuth2: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateTokenRequest'
            example:
              pin: "123456"
      responses:
        '200':
          description: Token is generated successfully
          headers:
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateTokenResponse'
              example: 
                response:
                  token: "550e8400-e29b-41d4-a716-446655440000"
        '400':
          description: "Missing required values or incorrect values or validation fails"
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Missing pin:
                  value:
                    errors:
                      - code: "10005"
                        message: "Required headers are missing."
        '401':
          description: Unauthorized
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                Invalid Token:
                  value:
                    errors:
                      - code: "250002"
                        message: "Invalid Authentication Information"
        '403':
          description: Forbidden
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Forbidden:
                  value:
                    errors:
                      - code: "40301"
                        message: "You do not have permission to access this resource."
        '404':
          description: Not Found
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                NotFound:
                  value:
                    errors:
                      - code: "10009"
                        message: "Resource not found."
        '500':
          description: Internal Server Error
          headers:
            APIErrorCode:
              $ref: '#/components/headers/APIErrorCode'
            APIErrorMsg:
              $ref: '#/components/headers/APIErrorMsg'
            BkndTransId:
              $ref: '#/components/headers/BkndTransId'
            transactionSrc:
              $ref: '#/components/headers/transactionSrc'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                InternalServerError:
                  value:
                    errors:
                      - code: "10006"
                        message: "A system error occurred."
components:
  parameters:
    transID:
      name: transID
      in: header
      required: true
      description: Transaction ID
      schema:
        type: string
    transactionSrc:
      name: transactionSrc
      in: header
      required: true
      description: Transaction Source
      schema:
        type: string
  headers:
    BkndTransId:
      description: The backend uuid transaction id.
      schema:
        type: string
    transactionSrc:
      description: Identifies the client/source application that is calling.
      schema:
        type: string
    APIErrorCode:
      description: The API error code.
      schema:
        type: string
    APIErrorMsg:
      description: The API error message
      schema:
        type: string
  schemas:
    GenerateTokenRequest:
      type: object
      properties:
        pin:
          type: string
          pattern: '^[0-9]{4,6}$'
          minLength: 4
          maxLength: 6
          description: The Pin for which the token is generated (4 to 6 digits, leading zeros allowed; e.g., 0007).
      required:
        - pin
      description: 'This request is sent to generate a token for a given Pin.'
      title: GenerateTokenRequest
    GenerateTokenResponse:
      type: object
      properties:
        response:
          type: object
          required:
            - token
          properties:
            token:
              type: string
              format: uuid
              description: Generated token for the given PIN.
      required:
        - response
      description: 'This response returns the generated token for the given Pin.'
      title: GenerateTokenResponse
    ErrorResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Error'
          description: "Standardized error object for responses and callbacks."
      description: 'This response is returned when an error occurs, containing a list of error objects with standardized error codes and messages.'
      title: ErrorResponse
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: "Error code"
        message:
          type: string
          description: "Human-readable error message providing additional context about the error."
      description: 'This object represents an error, containing a standardized error code and a human-readable message.'
      title: Error
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          x-tokenEndpointAuthMethod: client_secret_basic
          tokenUrl: https://onlinetools.ups.com/security/v1/oauth/token
          scopes: {}
